"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                  此为温习江湖(wweir)的个人.vimrc文件,                   "
"               不保证适合其它人，只希望其具有一些参考价值                "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"解决乱码
let &termencoding=&encoding
set fileencodings=utf-8,gbk,gb2312,gb18030,big5,ucs-bom,cp936
"设置主题色调为
set t_Co=256
colo molokai
""^$.*转义
set magic
""每行最长长度
set textwidth=78
""启用鼠标
set mouse=a
""高亮当前列
set cuc
set cul
"自动检测文本类型, 打开语法高亮
syntax enable
syntax on
filetype plugin indent on
filetype plugin on
""行号
set rnu
set nu
"自动缩进、
set autoindent
set smartindent
"自动换行
se wrap
set linebreak
""翻页边距
set so=3
""搜索
set ignorecase smartcase
set incsearch
set hlsearch
set showmatch
""关机前编辑文件恢复
set undodir=/tmp
set undofile
""折行
set foldmethod=indent
set foldlevel=3
""设置文件浏览器目录为当前目录
set bsdir=buffer
set autochdir

"自动添加tags文件
set tags+=./tags,./../tags
"<Space>缩进
:set shiftwidth=4
:set tabstop=4
"":set expandtab
set softtabstop=4

set autoread "文件修改自动载入
set backspace=indent,eol,start "可删除任意东西
set noswapfile "不要swap文件

"在terminal中启用Alt快捷键
set ttimeoutlen=1
for UseAlt in range(65, 90)+range(97, 122)
	exe "set <M-".nr2char(UseAlt).">=\<esc>".nr2char(UseAlt)
endfor

"快捷移动""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
noremap <A-w>  <Esc>:x<CR>
noremap <A-W>  <Esc>:w !sudo tee %
noremap <A-q>  <Esc>:q<CR>
noremap <A-Q>  <Esc>:q!<CR>
inoremap <A-O>  <c-o>O
nnoremap ： :
"保存为HTML
"let use_xhtml = 1

noremap <M-T>  <Esc>:TOhtml<CR>
nnoremap j gj
nnoremap k gk
nnoremap <A-j> gj
nnoremap <A-k> gk
inoremap <expr><M-h>    getline('.')[col('.')-2]!~"[0-9a-zA-Z_]" ? "\<Left>" : "<Esc>ba"
nnoremap <expr><M-h>    getline('.')[col('.')-2]!~"[0-9a-zA-Z_]" ? "\<Left>" : "b"
inoremap <expr><M-l>    getline('.')[col('.')] !~ "[0-9a-zA-Z_]" ? "\<Right>" : "<Esc>wa"
nnoremap <expr><M-l>    getline('.')[col('.')] !~ "[0-9a-zA-Z_]" ? "\<Right>" : "w"
inoremap <expr><M-j>    pumvisible() ? "<c-n>" : "<c-o>gj"
inoremap <expr><M-k>    pumvisible() ? "<c-p>" : "<c-o>gk"

""快捷输入""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
inoremap <expr>)    pumvisible() && getline('.')[col('.') - 2] == "(" ? ")<left>" : ")"
inoremap <expr>(    pumvisible() && getline('.')[col('.') - 2] == "(" ? ")<left>" : "()<left>"
inoremap <expr><CR> getline('.')[col('.')-2]=~"[{>]" && getline('.')[col('.')-1]=~"[}<]" ? "<left> <right><CR><Esc>ko" : "<CR>"
inoremap <expr>;    getline('.')[col('.') - 1] == $ ? ";" : "; "
inoremap <expr>s    getline('.')[col('.')-2]=="'" && getline('.')[col('.')-3]=~'\a' ? "s\<del>" : 's'
inoremap ,  ,<space>
inoremap '  <c-r>=ClosePair("\'")<CR>
cnoremap '  ''<Left>
inoremap "  <C-r>=ClosePair("\"")<CR>
cnoremap "  ""<Left>
inoremap (  ()<left>
cnoremap (  ()<left>
vnoremap ( \"zdi(<c-r>z)<esc>
inoremap （ （）<left>
vnoremap （ \"zdi（<c-r>z）<esc>
inoremap [  []<Left>
cnoremap [  []<left>
vnoremap [ \"zdi[<c-r>z]<esc>
inoremap ]  <c-r>=ClosePair(']')<CR>
inoremap {  {}<Left>
cnoremap {  {}<Left>
vnoremap { \"zdi{<c-r>z}<esc>
inoremap }  <c-r>=ClosePair('}')<CR>

""符号配对
function ClosePair(char)
	if getline('.')[col('.') - 1] == a:char
		return "\<Right>"
	elseif (a:char == "\'" || a:char == "\"" || a:char == "\`")
		return a:char.a:char."\<left>"
	else
		return a:char
	endif
endf
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if !isdirectory($HOME."/.vim")
	execute("!wget -P ~/.vim/autoload https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim")
	execute("!wget -P ~/.vim/colors https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim")
endif
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
"Plug 'Valloric/YouCompleteMe'
Plug 'Shougo/neocomplcache.vim'
Plug 'Shougo/neosnippet.vim'
Plug 'honza/vim-snippets'
call plug#end()

""neocomplete setting
""let g:neocomplete#enable_at_startup = 1
let g:neocomplcache_enable_at_startup = 1


""""背景透明
hi Normal ctermbg=none
